version: "3"
services:
    router:
        image: nginx
        volumes:
            - "./router/routes.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8080:80"
        depends_on:
            - gatekeeper
    gatekeeper:
        build: 
            context: "./gatekeeper"
            dockerfile: Dockerfile
        ports:
            - "3001:3000"
