version: "3"
services:
    router:
        build: 
            context: "./router"
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        environment:
            - "PORT=8080"
            - "GATEKEEPER_URL=http://gatekeeper:3000"
        depends_on:
            - gatekeeper
    gatekeeper:
        build: 
            context: "./gatekeeper"
            dockerfile: Dockerfile
        ports:
            - "3001:3000"
